### ISSUE TITLE
To Do List

### ISSUE THREAD

**Issue by guillemontecinos** [guillemontecinos/interactive-browser-multi#1]
# ToDo user testing
* [x] When playing notes, track previous note status to enable longer notes
   * [x] Admin End
   * [x] User End
* [x] Simulate sound at user side with tone. This implies the tempo has to be set from the admin
   * [x] Admin inform server it is playing
   * [x] User know when the admin is playing
   * [x] Implement admin velocity calculation based on stroke => calibrate `ln` curve
   * [ ] Ask Sokio for samples to replace tone synth
* [x] Allow user select their stroke and set it on admin and viewer side
   * [x] Make canvas automatically resize
   * [x] Avoid a dot being drawn when clicking a button
   * [x] Make buttons event assign more efficient, like using checkbox form
   * [x] Broadcast to admin and viewer
   * [x] Buttons CSS
   * [ ] Volume Control
* [ ] Allow user be able select amount of compasses (1-5)
   * [x] Write notes calculation on admin side
   * [x] Time numerator and denominator has to be broadcasted to update grid on client side
   * [ ] Update notes calculation on client side
* [x] Allow user chose scales
   * [x] Create key selector
   * [x] Create octave selector
   * [x] Broadcast octave events to admin
   * [x] Implement octave for each user on admin side
   * [x] Test octave implementation for 1+ users
   * [x] There's an issue with releasing notes on the client side
   * [x] Keep track of what happens with `previousNotes` on the admin side when changing the scale length
   * [x] Update numNotes on click
   * [x] Create an array that keeps track of the notes' numbers
   * [x] numNotes is being forcer from the admin, clean that
   * [x] Style ui
   * [ ] Display key, octave and scale at admin side
   * [x] On client side, disable jumping from C to B or vice versa.
* [x] Make grid visible
* [ ] Fix client's sound
* [x] Client clear is not clearing viewer

# Pending
## Client
* [ ] Force interface to be horizontal for mobile devices
* [ ] Test in phone

## Notes from Sokio
* [ ] Allow client to chose what channel to use. Server has to keep track of the available channels and let the users pick and switch whenever they want. Admin has to label each channel, and the names have to be transferred to the client side.
* [x] Make a visualization 3rd page.

## Reference
https://dev.to/paolodelia99/build-a-simple-chat-app-with-node-js-and-socket-io-apk
